# Generated by Django 4.2.7 on 2024-07-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnement',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
