# Generated by Django 4.2.7 on 2024-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanager', '0003_alter_approvisionnement_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='solde',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
