# Generated by Django 5.0.7 on 2024-09-02 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanager', '0004_alter_caisse_solde'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='media/pieces_justificatives/')),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True)),
                ('retrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashmanager.retrait')),
            ],
        ),
    ]
